services:
  valkey:
    image: valkey/valkey:8
    ports:
      - 6379:6379

  server:
    image: ghcr.io/erancihan/clair:latest
    depends_on:
      - valkey
    ports:
      - "4000:4000"
    volumes:
      - database:/opt/clair/database
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_FOLDER=/opt/clair/database
    command: ./clair.bin server

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: .opt/clair/database
      o: bind
