services:
  clair:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - clair-data:/opt/clair/database
      - clair-public:/opt/clair/public
    env_file: ".env"
    environment:
      - DB_FOLDER=/opt/clair/database
      - PUBLIC_PATH=/opt/clair/public
    command: ./clair.bin server

volumes:
  clair-data:
    driver: local
    driver_opts:
      type: none
      device: .opt/clair/data
      o: bind
  clair-public:
    driver: local
    driver_opts:
      type: none
      device: .opt/clair/public
      o: bind